- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: " terraform-2024040314341296480000000a.c3im8m4e8dks.us-east-1.rds.amazonaws.com" 
    login_user: "david"
    login_password: "devopspblproject"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: " terraform-2024040314341296480000000a.c3im8m4e8dks.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "lekan" }
    - { regexp: '^database_name_here', line: "wordpressdb" }
    - { regexp: '^password_here', line: "lekan12345" }
