pipeline {
	agent	any

	environment {
		ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
	}

	parameters {
		string(name: 'inventory', defaultValue: 'dev', description: 'Inventory file for environment to deploy configuration')
	}

	stages {
		
		stage('Initial cleanup') {
			steps {
				dir("${WORKSPACE}") {
					deleteDir()
				}
			}
		}

		stage('Checkout SCM') {
			steps {
				git branch: 'feature/jenkinspipeline-stage', url: 'https://github.com/Horleryheancarh/ansible-config-mgt.git'
			}
		}

		stage('Prepare Ansible For Execution') {
			steps {
				script {
					sh 'echo "${WORKSPACE}"'
					sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
				}
			}
		}

		stage('Run Ansible playbook') {
			steps {
				ansiblePlaybook colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml'
			}
		}

		stage('Cleanup') {
			steps {
				cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
			}
		}

	}
}