- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2024040314341296480000000a.c3im8m4e8dks.us-east-1.rds.amazonaws.com"
    login_user: "lekan"
    login_password: "lekan12345"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-2024040314341296480000000a.c3im8m4e8dks.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "lekan" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "lekan12345" }




